from typing import List, Dict, Any
from app.schemas.simulation import (
    SimulationScenarioRequest,
    SimulationScenarioResult,
    TrajectoryPoint
)


class SimulationEngine:
    """
    Interactive What-If Policy Simulation Sandbox.
    Allows MSDE planners to stress-test policy interventions:
    - Capital injections into industrial parks / PLI clusters
    - Seat quota alterations
    - Trainee incentive & stipend revisions
    Projects resulting gap contraction curves over 12M and 24M horizons.
    """

    def run_simulation(
        self,
        request: SimulationScenarioRequest,
        baseline_demand_total: int,
        baseline_supply_total: int
    ) -> SimulationScenarioResult:
        horizon = request.simulation_horizon_months
        
        # 1. Direct jobs generated by Capex injection (~3.8 direct technician jobs per Cr Capex in manufacturing)
        capex_jobs_created = int(round(request.capex_injection_cr * 3.8))

        # 2. Enhanced supply from extra seats & stipend boost on retention
        stipend_multiplier = 1.0 + (request.training_stipend_boost_pct / 100.0) * 0.4 # Higher stipend boosts completion & retention
        effective_additional_supply = int(round(request.additional_seats_sanctioned * 0.78 * 0.50 * stipend_multiplier))

        trajectory: List[TrajectoryPoint] = []
        cumulative_unmanaged_gap = 0
        cumulative_managed_gap = 0
        total_mitigated_headcount = 0

        # Start from base date 2026-04
        start_y, start_m = 2026, 4

        for m in range(1, horizon + 1):
            curr_y = start_y + (start_m + m - 2) // 12
            curr_m = ((start_m + m - 2) % 12) + 1
            period_str = f"{curr_y}-{curr_m:02d}"

            # Phased Capex effect (S-curve ramp up across months)
            phase_factor = min(1.0, (m / (horizon * 0.75)) ** 1.5)
            month_capex_demand = int(round((capex_jobs_created / horizon) * phase_factor))

            # Phased supply graduation effect (batches begin graduating from month 4 onwards)
            supply_phase = 0.20 if m < 4 else min(1.0, 0.20 + 0.80 * (m - 3) / max(horizon - 3, 1))
            month_sim_supply = int(round((effective_additional_supply / horizon) * supply_phase))

            m_base_demand = int(round(baseline_demand_total / 12.0 * (1.0 + 0.01 * m)))
            m_base_supply = int(round(baseline_supply_total / 12.0 * (1.0 + 0.005 * m)))

            # Total new demand created by industrial growth
            m_sim_demand = m_base_demand + month_capex_demand
            
            # Unmanaged gap without training seat augmentation
            m_unmanaged_gap = abs(m_sim_demand - m_base_supply)

            # Managed gap with training seat augmentation
            m_managed_supply = m_base_supply + month_sim_supply
            m_managed_gap = abs(m_sim_demand - m_managed_supply)

            month_improvement = max(0, m_unmanaged_gap - m_managed_gap)
            total_mitigated_headcount += month_improvement

            cumulative_unmanaged_gap += m_unmanaged_gap
            cumulative_managed_gap += m_managed_gap

            trajectory.append(
                TrajectoryPoint(
                    month_offset=m,
                    period=period_str,
                    baseline_gap=m_unmanaged_gap,
                    simulated_gap=m_managed_gap,
                    net_improvement=month_improvement
                )
            )

        efficiency_pct = round((total_mitigated_headcount / max(cumulative_unmanaged_gap, 1)) * 100.0, 1)
        efficiency_pct = max(efficiency_pct, round((effective_additional_supply / max(capex_jobs_created, 1)) * 100.0, 1))

        # Cost effectiveness calculation
        total_training_cost = request.additional_seats_sanctioned * 38000.0
        total_stipend_cost = request.additional_seats_sanctioned * (request.training_stipend_boost_pct / 100.0) * 12000.0
        total_intervention_cost = total_training_cost + total_stipend_cost
        
        placed_candidates = int(round(effective_additional_supply * 0.85))
        cost_per_placement = round(total_intervention_cost / max(placed_candidates, 1), 2)

        if efficiency_pct >= 25.0:
            verdict = (
                f"HIGHLY RECOMMENDED: The intervention reduces district demand-supply friction by {efficiency_pct}% "
                f"over {horizon} months with an estimated cost of ₹{cost_per_placement:,.0f} per candidate placed."
            )
        elif efficiency_pct >= 10.0:
            verdict = (
                f"VIABLE MODERATE IMPACT: Delivers {efficiency_pct}% gap mitigation; consider pairing with specialized "
                f"apprenticeship tie-ups to accelerate placement speed."
            )
        else:
            verdict = "MARGINAL RETURN: Gap reduction under 10%; redirect budget towards short-term modular bridge courses."

        return SimulationScenarioResult(
            scenario_name=request.scenario_name,
            target_sector=request.target_sector_code,
            target_district=request.target_district_code or "ALL_PILOT_DISTRICTS",
            baseline_total_gap=cumulative_unmanaged_gap,
            simulated_total_gap=cumulative_managed_gap,
            absolute_gap_reduction=total_mitigated_headcount,
            gap_mitigation_efficiency_pct=efficiency_pct,
            projected_additional_placements=placed_candidates,
            estimated_cost_per_placed_candidate_inr=cost_per_placement,
            policy_verdict=verdict,
            monthly_trajectory=trajectory
        )


simulation_engine = SimulationEngine()
