const fs = require('fs');
function getFiles(dir, files = []) {
  const fileList = fs.readdirSync(dir);
  for (const file of fileList) {
    const name = `${dir}/${file}`;
    if (fs.statSync(name).isDirectory()) {
      getFiles(name, files);
    } else if (name.endsWith('.tsx')) {
      files.push(name);
    }
  }
  return files;
}

const files = getFiles('./src');
for (const file of files) {
  let content = fs.readFileSync(file, 'utf8');
  
  // Clean up exactly the weird nested strings generated by the double replacement
  content = content.replace(/\{Boolean\(([^)]+)\)\s*\{[^}]+\}\s*\(\s*\{[^}]+\}\s*\(\s*\(/g, match => {
     const m = match.match(/\{Boolean\(([^)]+)\)/);
     return `{Boolean(${m[1]}) && (`;
  });
  
  // Handle any triple nested ones just in case
  content = content.replace(/\{Boolean\(([^)]+)\)\s*(?:\{[^}]+\}\s*\(\s*)+\(/g, match => {
     const m = match.match(/\{Boolean\(([^)]+)\)/);
     return `{Boolean(${m[1]}) && (`;
  });

  // Handle the span tags
  content = content.replace(/\{Boolean\(([^)]+)\)\s*(?:\\\&\\\&)+/g, match => {
     const m = match.match(/\{Boolean\(([^)]+)\)/);
     return `{Boolean(${m[1]}) &&`;
  });
  content = content.replace(/\{Boolean\(([^)]+)\)\s*\&\&\s*\<span/g, match => {
     const m = match.match(/\{Boolean\(([^)]+)\)/);
     return `{Boolean(${m[1]}) && <span`;
  });

  fs.writeFileSync(file, content);
}
