from fastapi import APIRouter, Depends, Query
from app.core.auth import require_role
from app.services.llm_policy_chat import llm_policy_engine, PolicyChatResponse

router = APIRouter()

@router.post("/ask", response_model=PolicyChatResponse)
def ask_sovereign_llm(
    query: str = Query("Why is unemployment rising in Pune for Welders, and what should I do?", description="Natural language policy question")
):
    """
    Sovereign LLM (RAG) Policy Chat Endpoint (Phase 1).
    Takes a natural language query from a planner, accesses the MSDE backend securely, 
    and returns a drafted policy memo generated by the AI agent.
    """
    return llm_policy_engine.generate_policy_memo(query=query)
